# Database
spring.datasource.url=jdbc:mysql://localhost:3306/preloved_db?useSSL=false&serverTimezone=Asia/Jakarta
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Rate Limiting
app.rate-limiting.enabled=true
app.rate-limiting.max-requests=5
app.rate-limiting.time-window-minutes=1